### ISSUE TITLE
Metadata tagging 

### ISSUE THREAD

**Issue by trustosas** [devlocalhost/pyspodl#3]

**Comment by devlocalhost** [comment]
I tried experimenting with this once, but it was kinda confusing. If you have any ideas, please let me know

Edit: ill give it a try again, but your other [request](https://github.com/devlocalhost/pyspodl/issues/2) has priority

**Comment by trustosas** [comment]
<strike>Spotipy can provide track metadata</strike> More appropriately, https://api.spotify.com/v1/tracks/ endpoint provide metadata on the track

**Comment by devlocalhost** [comment]
> Spotipy can provide track metadata

I mean, how can I set/edit metadata? That's the problem. When downloading a song, it doesn't download the metadata too, so you'll have to do this manually. As I said before, I experimented once, but it was confusing. I did a research again, and I found some stuff. But I'll focus on this later

**Comment by trustosas** [comment]
![Screenshot_20220801_180237](https://user-images.githubusercontent.com/74086441/182204753-2e16ca49-5384-4c57-bdc0-ebefce4b3946.jpg)
Here's the fields I hope to fill with the tagging feature. The screenshot is from Automatag, a tagging app for Android.

**Comment by devlocalhost** [comment]
> ![Screenshot_20220801_180237](https://user-images.githubusercontent.com/74086441/182204753-2e16ca49-5384-4c57-bdc0-ebefce4b3946.jpg) Here's the fields I hope to fill with the tagging feature. The screenshot is from Automatag, a tagging app for Android.

Is "disc number" and "count" really needed? I think title, artist, genre, track number and count, album name and year are the only needed ones. (why not album artist? Because of "artist")

**Comment by trustosas** [comment]
I ran a test for tagging with this snippet, and it works ok. music tag based on mutagen was the solution. Album total & Disc total weren't tagged however:

import os
import spotipy
import requests as r
from spotipy.oauth2 import SpotifyClientCredentials
import music_tag
import PIL

file = music_tag.load_file("/storage/emulated/0/Python/pyspodl/Bluewerks_-_I am Loving - Spotify Singles.ogg")

os.environ["SPOTIPY_CLIENT_ID"] = 'GO GET YOURS!'
os.environ["SPOTIPY_CLIENT_SECRET"] = 'GO GET YOURS!'

spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

track = spotify.track('4IJsomqPm1O6fVPkRlP2n3')
#album = spotify.album(track['album']['id'])
#print(album)
#print(track)

print(track['name']) #Track name
print(', '.join([i['name'] for i in track['artists']])) #Track artist(s)
#Genre(s) unavailable :'(
print(track['track_number'], track['album']['total_tracks'])
print(1, 1) #Default values for disc number & total
print(track['album']['name']) #Album name

#proper capitalization of album type
if track["album"]["album_type"] == 'ep':
	track["album"]["album_type"] = track["album"]["album_type"].upper()
else:
	track["album"]["album_type"] = track["album"]["album_type"].title()

print(track["album"]["album_type"]) #Album type: Single/EP/Album
print(', '.join([i['name'] for i in track['album']['artists']])) #Album artist(s)
print(track['album']['release_date']) #Album release date

metadata = {'title': track['name'], 'artist': ', '.join([i['name'] for i in track['artists']]), 'tracknumber': track['track_number'], 'totaltracks': track['album']['total_tracks'], 'discnumber': 1, 'totaldiscs': 1, 'album': track["album"]["name"] + f'{ " - " if track["album"]["album_type"] != "Album" else ""}' + f'{ track["album"]["album_type"] if track["album"]["album_type"] != "Album" else ""}','albumartist': ', '.join([i['name'] for i in track['album']['artists']]), 'year': track['album']['release_date']}

print(metadata)

img_data = r.get(track['album']['images'][0]['url']).content
with open('cover.jpg', 'wb') as f:
	f.write(img_data)

with open('cover.jpg', 'rb') as f:
	file['artwork'] = f.read()

for key, value in metadata.items():
	file[key] = value

file.save()

Result:

I am Loving - Spotify Singles
Bluewerks, Oatmello
3 8
1 1
Bluewerks: Spotify Singles
Single
Bluewerks
2022-05-04
{'title': 'I am Loving - Spotify Singles', 'artist': 'Bluewerks, Oatmello', 'tracknumber': 3, 'totaltracks': 8, 'discnumber': 1, 'totaldiscs': 1, 'album': 'Bluewerks: Spotify Singles - Single', 'albumartist': 'Bluewerks', 'year': '2022-05-04'}

[Program finished]

I did use spotipy, because I couldn't figure out the whole auth process. Please find a way to remove the dependency. I also stuck to Automatag's syntax because my current library was tagged with it.

**Comment by devlocalhost** [comment]
Well I found https://github.com/nicfit/eyeD3 and https://pypi.org/project/music-tag/ so I'll give those a try

**Comment by devlocalhost** [comment]
> please find a way to remove the dependecy

What dependecy?

**Comment by devlocalhost** [comment]
Also, no need to use another library (spotipy, as you said) when the Spotify API already gives you the data (check https://developer.spotify.com/console/get-album/?id=&market= note: you need to login to see the example data)

**Comment by trustosas** [comment]
> Well I found https://github.com/nicfit/eyeD3 and https://pypi.org/project/music-tag/ so I'll give those a try
#
When you have tried music tag, take a look at the snippet I sent below:

> I ran a test for tagging with this snippet, and it works ok. music tag based on mutagen was the solution. Album total & Disc total weren't tagged however:
> 
> import os import spotipy import requests as r from spotipy.oauth2 import SpotifyClientCredentials import music_tag import PIL
> 
> file = music_tag.load_file("/storage/emulated/0/Python/pyspodl/Bluewerks_-_I am Loving - Spotify Singles.ogg")
> 
> os.environ["SPOTIPY_CLIENT_ID"] = 'GO GET YOURS!' os.environ["SPOTIPY_CLIENT_SECRET"] = 'GO GET YOURS!'
> 
> spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())
> 
> track = spotify.track('4IJsomqPm1O6fVPkRlP2n3') #album = spotify.album(track['album']['id']) #print(album) #print(track)
> 
> print(track['name']) #Track name print(', '.join([i['name'] for i in track['artists']])) #Track artist(s) #Genre(s) unavailable :'( print(track['track_number'], track['album']['total_tracks']) print(1, 1) #Default values for disc number & total print(track['album']['name']) #Album name
> 
> #proper capitalization of album type if track["album"]["album_type"] == 'ep': track["album"]["album_type"] = track["album"]["album_type"].upper() else: track["album"]["album_type"] = track["album"]["album_type"].title()
> 
> print(track["album"]["album_type"]) #Album type: Single/EP/Album print(', '.join([i['name'] for i in track['album']['artists']])) #Album artist(s) print(track['album']['release_date']) #Album release date
> 
> metadata = {'title': track['name'], 'artist': ', '.join([i['name'] for i in track['artists']]), 'tracknumber': track['track_number'], 'totaltracks': track['album']['total_tracks'], 'discnumber': 1, 'totaldiscs': 1, 'album': track["album"]["name"] + f'{ " - " if track["album"]["album_type"] != "Album" else ""}' + f'{ track["album"]["album_type"] if track["album"]["album_type"] != "Album" else ""}','albumartist': ', '.join([i['name'] for i in track['album']['artists']]), 'year': track['album']['release_date']}
> 
> print(metadata)
> 
> img_data = r.get(track['album']['images'][0]['url']).content with open('cover.jpg', 'wb') as f: f.write(img_data)
> 
> with open('cover.jpg', 'rb') as f: file['artwork'] = f.read()
> 
> for key, value in metadata.items(): file[key] = value
> 
> file.save()
> 
> Result:
> 
> I am Loving - Spotify Singles Bluewerks, Oatmello 3 8 1 1 Bluewerks: Spotify Singles Single Bluewerks 2022-05-04 {'title': 'I am Loving - Spotify Singles', 'artist': 'Bluewerks, Oatmello', 'tracknumber': 3, 'totaltracks': 8, 'discnumber': 1, 'totaldiscs': 1, 'album': 'Bluewerks: Spotify Singles - Single', 'albumartist': 'Bluewerks', 'year': '2022-05-04'}
> 
> [Program finished]
> 
> I did use spotipy, because I couldn't figure out the whole auth process. Please find a way to remove the dependency. I also stuck to Automatag's syntax because my current library was tagged with it.

**Comment by trustosas** [comment]
> > ![Screenshot_20220801_180237](https://user-images.githubusercontent.com/74086441/182204753-2e16ca49-5384-4c57-bdc0-ebefce4b3946.jpg) Here's the fields I hope to fill with the tagging feature. The screenshot is from Automatag, a tagging app for Android.
> 
> Is "disc number" and "count" really needed? I think title, artist, genre, track number and count, album name and year are the only needed ones. (why not album artist? Because of "artist")

"Album artist" makes it very clear who owns the album (In the case of album compilations consisting of various artists, the artist who works on a single track is NOT necessarily the album artist as you seem to have assumed). I agree with you on disc number and count; I default both to a value of 1. Apps like TIDAL take disc count into consideration but Spotify doesn't.
In addition, I make use of a player (Poweramp) that supports album artist tag
![Screenshot_20220802_062233](https://user-images.githubusercontent.com/74086441/182298281-89e1955c-cd19-4ac4-b499-a8af15c5f044.jpg)

**Comment by trustosas** [comment]
> I ran a test for tagging with this snippet, and it works ok. music tag based on mutagen was the solution. Album total & Disc total weren't tagged however:
> 
> import os import spotipy import requests as r from spotipy.oauth2 import SpotifyClientCredentials import music_tag import PIL
> 
> file = music_tag.load_file("/storage/emulated/0/Python/pyspodl/Bluewerks_-_I am Loving - Spotify Singles.ogg")
> 
> os.environ["SPOTIPY_CLIENT_ID"] = 'GO GET YOURS!' os.environ["SPOTIPY_CLIENT_SECRET"] = 'GO GET YOURS!'
> 
> spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())
> 
> track = spotify.track('4IJsomqPm1O6fVPkRlP2n3') #album = spotify.album(track['album']['id']) #print(album) #print(track)
> 
> print(track['name']) #Track name print(', '.join([i['name'] for i in track['artists']])) #Track artist(s) #Genre(s) unavailable :'( print(track['track_number'], track['album']['total_tracks']) print(1, 1) #Default values for disc number & total print(track['album']['name']) #Album name
> 
> #proper capitalization of album type if track["album"]["album_type"] == 'ep': track["album"]["album_type"] = track["album"]["album_type"].upper() else: track["album"]["album_type"] = track["album"]["album_type"].title()
> 
> print(track["album"]["album_type"]) #Album type: Single/EP/Album print(', '.join([i['name'] for i in track['album']['artists']])) #Album artist(s) print(track['album']['release_date']) #Album release date
> 
> metadata = {'title': track['name'], 'artist': ', '.join([i['name'] for i in track['artists']]), 'tracknumber': track['track_number'], 'totaltracks': track['album']['total_tracks'], 'discnumber': 1, 'totaldiscs': 1, 'album': track["album"]["name"] + f'{ " - " if track["album"]["album_type"] != "Album" else ""}' + f'{ track["album"]["album_type"] if track["album"]["album_type"] != "Album" else ""}','albumartist': ', '.join([i['name'] for i in track['album']['artists']]), 'year': track['album']['release_date']}
> 
> print(metadata)
> 
> img_data = r.get(track['album']['images'][0]['url']).content with open('cover.jpg', 'wb') as f: f.write(img_data)
> 
> with open('cover.jpg', 'rb') as f: file['artwork'] = f.read()
> 
> for key, value in metadata.items(): file[key] = value
> 
> file.save()
> 
> Result:
> 
> I am Loving - Spotify Singles Bluewerks, Oatmello 3 8 1 1 Bluewerks: Spotify Singles Single Bluewerks 2022-05-04 {'title': 'I am Loving - Spotify Singles', 'artist': 'Bluewerks, Oatmello', 'tracknumber': 3, 'totaltracks': 8, 'discnumber': 1, 'totaldiscs': 1, 'album': 'Bluewerks: Spotify Singles - Single', 'albumartist': 'Bluewerks', 'year': '2022-05-04'}
> 
> [Program finished]
> 
> I did use spotipy, because I couldn't figure out the whole auth process. Please find a way to remove the dependency. I also stuck to Automatag's syntax because my current library was tagged with it

Here's the source file (rename to .py):
[tag.txt](https://github.com/devlocalhost/pyspodl/files/9239175/tag.txt)

**Comment by trustosas** [comment]
On [my earlier comment](https://github.com/devlocalhost/pyspodl/issues/3#issuecomment-1201715132), this is the source file:
[tag.py.txt](https://github.com/devlocalhost/pyspodl/files/9240981/tag.py.txt)

It tags a file in my local storage so adjust filepaths appropriately. It's not difficult to add tags, music-tag module makes it really easy.
Let me know what you think of it.

> > please find a way to remove the dependecy
> 
> What dependecy?

I meant Spotipy 
(Side note, Spotify doesn't provide genre metadata :( )

**Comment by devlocalhost** [comment]
> On [my earlier comment](https://github.com/devlocalhost/pyspodl/issues/3#issuecomment-1201715132), this is the source file: [tag.py.txt](https://github.com/devlocalhost/pyspodl/files/9240981/tag.py.txt)
> 
> It tags a file in my local storage so adjust filepaths appropriately. It's not difficult to add tags, music-tag module makes it really easy. Let me know what you think of it.
> 
> > > please find a way to remove the dependecy
> > 
> > 
> > What dependecy?
> 
> I meant Spotipy (Side note, Spotify doesn't provide genre metadata :( )

I'm going to experiment and see

**Comment by devlocalhost** [comment]
So I did something
![Screenshot_20220804-123742](https://user-images.githubusercontent.com/56504654/182815951-7aa62731-2c21-47f1-b1fa-23eff1e77020.png)

but for some reason poweramp won't read the tags
![Screenshot_20220804-123420](https://user-images.githubusercontent.com/56504654/182815982-b7887fcc-189b-40e3-9703-1e02658071b9.png)

But, mpv does read the tags 
![Screenshot_20220804-123358](https://user-images.githubusercontent.com/56504654/182816029-dba4f8f3-3a66-4697-9e15-6a31b9169084.png)

But vlc doesn't, it also won't play the song for some reason. I don't know why

**Comment by devlocalhost** [comment]
Also, about cover, I am not sure what exactly to do with that. music_tag requires pil (pillow) which is HUGE, so I'm not sure what to do

Edit: I installed pil to experiment, but i had issues

**Comment by devlocalhost** [comment]
Weird. Saving the cover works
![Screenshot_20220804-125033](https://user-images.githubusercontent.com/56504654/182818766-85746387-85b6-46e3-938f-ed2608ff8836.png)

But it also throws this: (but it does work)

```
Title: Cardigan
Artist(s): Don Toliver
Track count: 3
Album name: Heaven Or Hell
Album artist: Don Toliver
Total tracks: 12
Year: 2020
{'album': 'Heaven Or Hell',
 'albumartist': 'Don Toliver',
 'artist': 'Don Toliver',
 'title': 'Cardigan',
 'totaltracks': 12,
 'year': '2020'}
Downloading cover...
Saving metadata...
Saving cover...
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 88, in __init__
    crc, segments) = struct.unpack("<4sBBqIIiB", header)
struct.error: unpack requires a buffer of 27 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 587, in save
    self.tags._inject(filething.fileobj, padding)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/oggvorbis.py", line 147, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 436, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 228, in renumber
    page = OggPage(fileobj)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 90, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.ogg.error: unable to read full header; got b'\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 44, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/music_tag/file.py", line 374, in save
    self.mfile.save(**kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 589, in save
    reraise(self._Error, e, sys.exc_info()[2])
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/_util.py", line 43, in reraise
    raise tp(value).with_traceback(tb)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 587, in save
    self.tags._inject(filething.fileobj, padding)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/oggvorbis.py", line 147, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 436, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 228, in renumber
    page = OggPage(fileobj)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/mutagen/ogg.py", line 90, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.oggvorbis.OggVorbisHeaderError: unable to read full header; got b'\x00
'

[Program finished]
```

**Comment by devlocalhost** [comment]
I think this happens because of the file (track)

librespot gives a ogg/vorbis file, so it must have the ogg extension. Instead, I use m4a/mp3

**Comment by devlocalhost** [comment]
The script I made:

Test if you can, and let me know if it works

```py
from music_tag import load_file
from requests import get
from pprint import pprint

auth = {"Authorization": "Bearer TOKEN_HERE"}
id = '0Li1OuXXfi7950ilZUFGkF'

resp = get(f'https://api.spotify.com/v1/tracks/{id}', headers=auth).json()

file = load_file('Don Toliver_-_Cardigan.mp3')

album_artist = resp['album']['artists'][0]['name']
track_num = resp['track_number']
#disc_num = resp['disc_number']
title = resp['name']
artists = ', '.join(i['name'] for i in resp['artists'])
album_name = resp['album']['name']
year = resp['album']['release_date'].split('-')[0]
total_tracks = resp['album']['total_tracks']

print(f'Title: {title}\nArtist(s): {artists}\nTrack count: {track_num}\nAlbum name: {album_name}\nAlbum artist: {album_artist}\nTotal tracks: {total_tracks}\nYear: {year}')

#metadata = {'title': title, 'artist': artists, 'totaltracks': total_tracks, 'discnumber': disc_num, 'totaldiscs': track_num, 'album': album_name, 'albumartist': ', '.join([i['name'] for i in resp['album']['artists']]), 'year': year}

metadata = {'title': title, 'artist': artists, 'totaltracks': total_tracks, 'album': album_name, 'albumartist': ', '.join([i['name'] for i in resp['album']['artists']]), 'year': year}

pprint(metadata)

print('Downloading cover...')

with open('cover.jpg', 'wb') as cover_img:
    cover_img.write(get(resp['album']['images'][0]['url']).content)
    
print('Saving metadata...')

for key, value in metadata.items():
    file[key] = value
    
print('Saving cover...')

with open('cover.jpg', 'rb') as img_in:
    file['artwork'] = img_in.read()
    
file.save()
```

**Comment by trustosas** [comment]
Testing it now.

**Comment by trustosas** [comment]
Here's my edit:
```python
from music_tag import load_file
from requests import get

auth = {"Authorization": "Bearer TOKEN"}
id = '5tXMmaLkR8xYXXBkRCDj0k'

resp = get(f'https://api.spotify.com/v1/tracks/{id}', headers=auth).json()

file = load_file('/storage/emulated/0/Python/pyspodl/Bluewerks_-_Cheezy Does It.ogg')

album_artist = resp['album']['artists'][0]['name']
track_num = resp['track_number']
disc_num = resp['disc_number']
title = resp['name']
artists = ', '.join(i['name'] for i in resp['artists'])
album_name = resp['album']['name']
year = resp['album']['release_date'].split('-')[0]
total_tracks = resp['album']['total_tracks']

print(f'Title: {title}\nArtist(s): {artists}\nTrack count: {track_num}\nAlbum name: {album_name}\nAlbum artist: {album_artist}\nTotal tracks: {total_tracks}\nYear: {year}')

#added track number and removed disc number and disc total
metadata = {'title': title, 'artist': artists, 'tracknumber': track_num, 'totaltracks': total_tracks, 'album': album_name, 'albumartist': ', '.join([i['name'] for i in resp['album']['artists']]), 'year': year}

print('Downloading cover...')

with open('cover.jpg', 'wb') as cover_img:
    cover_img.write(get(resp['album']['images'][0]['url']).content)
    
print('Saving metadata...')

for key, value in metadata.items():
    file[key] = value
    
print('Saving cover...')

#added a try block to prevent a crashes
with open('cover.jpg', 'rb') as img_in:
    try:
    	file['artwork'] = img_in.read()
    except:
    	pass
    
file.save()
```
I made comments to the areas I made changes.
The only issue to me is that the total tracks field is not getting filled at the end file:
![Screenshot_20220804_125916](https://user-images.githubusercontent.com/74086441/182842603-971eb355-b48a-497e-9db2-3f5e808354ff.jpg)


> I think this happens because of the file (track)
> 
> librespot gives a ogg/vorbis file, so it must have the ogg extension. Instead, I use m4a/mp3

It crashes nonetheless. I changed the extension to .ogg in the downloader script and it happens still. The fix was a try/except block as the error isn't breaking functionality..

Could you also rename the file to get rid of the underscores? They aren't necessary in local storage.

I removed pprint. I don't find it necessary.

**Comment by devlocalhost** [comment]
> Here's my edit:
> 
> ```python
> from music_tag import load_file
> from requests import get
> 
> auth = {"Authorization": "Bearer TOKEN"}
> id = '5tXMmaLkR8xYXXBkRCDj0k'
> 
> resp = get(f'https://api.spotify.com/v1/tracks/{id}', headers=auth).json()
> 
> file = load_file('/storage/emulated/0/Python/pyspodl/Bluewerks_-_Cheezy Does It.ogg')
> 
> album_artist = resp['album']['artists'][0]['name']
> track_num = resp['track_number']
> disc_num = resp['disc_number']
> title = resp['name']
> artists = ', '.join(i['name'] for i in resp['artists'])
> album_name = resp['album']['name']
> year = resp['album']['release_date'].split('-')[0]
> total_tracks = resp['album']['total_tracks']
> 
> print(f'Title: {title}\nArtist(s): {artists}\nTrack count: {track_num}\nAlbum name: {album_name}\nAlbum artist: {album_artist}\nTotal tracks: {total_tracks}\nYear: {year}')
> 
> #added track number and removed disc number and disc total
> metadata = {'title': title, 'artist': artists, 'tracknumber': track_num, 'totaltracks': total_tracks, 'album': album_name, 'albumartist': ', '.join([i['name'] for i in resp['album']['artists']]), 'year': year}
> 
> print('Downloading cover...')
> 
> with open('cover.jpg', 'wb') as cover_img:
>     cover_img.write(get(resp['album']['images'][0]['url']).content)
>     
> print('Saving metadata...')
> 
> for key, value in metadata.items():
>     file[key] = value
>     
> print('Saving cover...')
> 
> #added a try block to prevent a crashes
> with open('cover.jpg', 'rb') as img_in:
>     try:
>     	file['artwork'] = img_in.read()
>     except:
>     	pass
>     
> file.save()
> ```
> 
> I made comments to the areas I made changes. The only issue to me is that the total tracks field is not getting filled at the end file: ![Screenshot_20220804_125916](https://user-images.githubusercontent.com/74086441/182842603-971eb355-b48a-497e-9db2-3f5e808354ff.jpg)
> 
> > I think this happens because of the file (track)
> > librespot gives a ogg/vorbis file, so it must have the ogg extension. Instead, I use m4a/mp3
> 
> It crashes nonetheless. I changed the extension to .ogg in the downloader script and it happens still. The fix was a try/except block as the error isn't breaking functionality..
> 
> Could you also rename the file to get rid of the underscores? They aren't necessary in local storage.
> 
> I removed pprint. I don't find it necessary.

1. Pprint was there for testing (formatting json, so it's easier to read)
2. I can't really remove underscores. It's a feature to remove spaces, and "illegal" characters (characters that might cause a "mess") like the dollar sign, hashtag, etc. Yes, it looks bad, but I also don't want to type a backslash every space when trying to play a file in tty for example (File Name -> File\ Name)
3. I am not sure about total tracks. I'll see what I can do. Maybe it's "tracktotal" instead of "total tracks"?

**Comment by devlocalhost** [comment]
Tip: no need to use "/storage/emulated/0". You can use "/sdcard" instead, for example, "/sdcard/Python/pyspodl"

**Comment by devlocalhost** [comment]
Not related to this, but I noticed that I've filename is kinda "broken". It does not really "clean" (remove unwanted characters) the filename, like it does in the local version of pyspodl. I should've pushed the changes I made locally, but now I can't (I can't use my laptop)

Another thing, I can remove this feature, but for example, when you're moving a file with a character that your phone or PC doesn't like, it will fail. That's why I added this feature. Sometimes, moving the music I downloaded to a different folder would fail, just because of a few characters in the filename

**Comment by devlocalhost** [comment]
> Not related to this, but I noticed that I've filename is kinda "broken". It does not really "clean" (remove unwanted characters) the filename, like it does in the local version of pyspodl. I should've pushed the changes I made locally, but now I can't (I can't use my laptop)
> 
> Another thing, I can remove this feature, but for example, when you're moving a file with a character that your phone or PC doesn't like, it will fail. That's why I added this feature. Sometimes, moving the music I downloaded to a different folder would fail, just because of a few characters in the filename

Actually, what I could do is replace only the characters that cause a mess, for example #, $, " ' ", ' " ', :, ;, etc

**Comment by devlocalhost** [comment]
If there's nothing else to fix/add, I will push this feature in August 12

**Comment by devlocalhost** [comment]
![Screenshot_20220810-180513](https://user-images.githubusercontent.com/56504654/183939245-cbab92cd-7c07-4615-8d1f-077e8c08dcb1.png)
![Screenshot_20220810-180519](https://user-images.githubusercontent.com/56504654/183939257-e4cf2038-6939-4dac-bf6b-ca8fac83b1dd.png)
![Screenshot_20220810-180527](https://user-images.githubusercontent.com/56504654/183939266-436c0168-0521-4cb7-9fe4-483b2404b5bc.png)

This, and #2 will be pushed very soon

**Comment by devlocalhost** [comment]
![IMG_20220810_180924_217](https://user-images.githubusercontent.com/56504654/183940067-ba18d70a-018a-4adc-8d86-fbf96bc2280d.jpg)
