### ISSUE TITLE
gettoken fails: error invalid_client

### ISSUE THREAD

**Issue by onny** [devlocalhost/pyspodl#7]
Response from the spotify API is

```
{'error': 'invalid_client', 'error_description': 'Invalid client'}
```

I have registered a new app in my premium account. Does pyspodl still work?

**Comment by devlocalhost** [comment]
> Response from the spotify API is
> 
> ```
> {'error': 'invalid_client', 'error_description': 'Invalid client'}
> ```
> 
> I have registered a new app in my premium account. Does pyspodl still work?

Can you please explain how did this happen?

**Comment by onny** [comment]
I put my client id and secret into the script like this

```
#!/usr/bin/python3

from requests import post

CLIENT_ID = 'HIDDEN******'
CLIENT_SECRET = 'HIDDEN******'
AUTH_URL = 'https://accounts.spotify.com/api/token'

resp = post(AUTH_URL, {'grant_type': 'client_credentials', 'client_id': CLIENT_ID, 'client_secret': CLIENT_SECRET}).json()

print(resp)

print(resp['access_token'])
```

ran the script and got the response. Does this still work or is my account banned?

**Comment by devlocalhost** [comment]
> I put my client id and secret into the script like this
> 
> ```
> #!/usr/bin/python3
> 
> from requests import post
> 
> CLIENT_ID = 'HIDDEN******'
> CLIENT_SECRET = 'HIDDEN******'
> AUTH_URL = 'https://accounts.spotify.com/api/token'
> 
> resp = post(AUTH_URL, {'grant_type': 'client_credentials', 'client_id': CLIENT_ID, 'client_secret': CLIENT_SECRET}).json()
> 
> print(resp)
> 
> print(resp['access_token'])
> ```
> 
> ran the script and got the response. Does this still work or is my account banned?

No, I do not think your account is banned, I get the same error too: `{'error': 'invalid_client'}`. I'll investigate and update

**Comment by devlocalhost** [comment]
Sorry, I actually do not face that issue (I did first, because I didn't add my token and ID). Are you sure you're using the correct client ID and secret?

**Comment by devlocalhost** [comment]
this may possibly not happen anymore
